apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sa-ingress
spec:
  backend:
    serviceName: nginx
    servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sa-fanout-ingress
  annotations:
    ingress.appscode.com/type: NodePort
spec:
  rules:
  - http:
      port: '8989'
      nodePort: '32666'
      paths:
      - path: /
        backend:
          serviceName: echoserver
          servicePort: 8080
      - path: /nginx
        backend:
          serviceName: nginx
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sa-nginx-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8899
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: extensions/v1beta1
kind: Deployment                                          # 1
metadata:
  name: sa-frontend
spec:
  replicas: 2                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate:
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: sa-frontend                                  # 6
    spec:
      containers:
        - image: rinormaloku/sentiment-analysis-frontend
          imagePullPolicy: Always                         # 7
          name: sa-frontend
          ports:
            - containerPort: 80




# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: sentiment-analysis
#   annotations:
#     ingress.appscode.com/type: NodePort
# spec:
#   rules:
#   - host: localhost
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: sa-frontend
#           servicePort: 80

# apiVersion: voyager.appscode.com/v1beta1
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: sentiment-analysis
#   annotations:
#     ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#   - http:
#     port: '8989'
#     paths:
#       - path: /first
#         backend:
#           serviceName: sa-frontend
#           servicePort: 5678


# kind: Ingress
# metadata:
#   name: test-ingress
#   namespace: default
#   annotations:
#     ingress.appscode.com/type: NodePort
# spec:
#   rules:
#   - host: one.example.com
#     http:
#       port: '8989'
#       nodePort: '32666'
#       paths:
#       - path: /t1
#         backend:
#           serviceName: sa-frontend
#           servicePort: '80'

#   - host: other.example.com
#     http:
#       port: '8989'
#       nodePort: '32666'
#       paths:
#       - backend:
#           serviceName: test-server
#           servicePort: '80'
#   - host: appscode.example.com
#     tcp:
#       port: '4343'
#       nodePort: '32667'
#       backend:
#         serviceName: test-server
#         servicePort: '80'
